captcha:
  keylong: 4
  imgwidth: 120
  imgheight: 40
casbin:
  modelpath: ./resource/rbac_model.conf
jwt:
  signingkey: qmPlus
log:
  prefix: '[GIN-VUE-ADMIN]'
  logfile: true
  stdout: DEBUG
  file: DEBUG
mysql:
  username: test
  password: "123456"
  path: 127.0.0.1:3306
  dbname: admin
  config: charset=utf8&parseTime=True&loc=Local
  maxidleconns: 10
  maxopenconns: 10
  logmode: true
qiniu:
  accesskey: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  secretkey: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
sqlite:
  username: ""
  password: ""
  path: db/db.db
  config: loc=Asia/Shanghai
  logmode: true
system:
  usemultipoint: false
  env: public
  addr: 8888
  dbtype: mysql
